package Items;

public enum DrinkTypeENUM {
    BEER, WINE, VODKA, BRANDY, CHAMPAGNE, WHISKEY,
    TEQUILA, RUM, VERMUTH, LIQUOR, JARERMEISTER, JUICE,
    COFFEE, GREEN_TEA, BLACK_TEA, MILK, WATER, SODA
}
